name: Build and deploy Node.js project to Azure Function App - marvel-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./marvel-azure-functions"
  NODE_VERSION: "20.x"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4

      - name: Resolve Project Dependencies Using Npm
        shell: pwsh
        run: |
          Push-Location ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          Pop-Location

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: marvel-azure-functions # extract artifact to this folder

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B0114E6FA7E8447BA3B50C7CFF65B8AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CEBBD8F87593435BBC2325EC2BFD787B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_049EE3BC37E7448DB161572AC93A56C3 }}

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: "marvel-api"
          slot-name: "Production"
          package: ./marvel-azure-functions
